apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::392133515518:role/capstone-project-eks-node-group-NodeInstanceRole-7MWO2T6S8OJ1
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::392133515518:user/capstone
      username: capstone
      groups:
        - system:masters
